name: rmux
settings:
  - SubcommandRequired
  - VersionlessSubcommands
  - InferSubcommands
  - ColoredHelp
args:
  - tmux_command:
      global: true
      help: tmux command to use
      short: t
      long: command
      value_name: COMMAND
      env: RMUX_COMMAND
  - config_dir:
      global: true
      help: configuration directory to use
      short: c
      long: config-dir
      value_name: DIR
      env: RMUX_CONFIG
subcommands:
  - list:
      settings:
        - ColoredHelp
      about: List all configured projects
      alias: ls
  - start:
      settings:
        - ColoredHelp
      about: Start a project as a tmux session
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            required: true
            index: 1
        - template:
            help: template file for generating tmux commands
            short: m
            long: template
            value_name: TEMPLATE
        - attach:
            help: force attach the session
            short: a
            long: attach
            conflicts_with: no_attach
        - no_attach:
            help: don't automatically attach the session
            short: d
            long: no-attach
        - debug:
            help: only print tmux command source without actually running tmux
            long: debug
            short: D
        - verbose:
            help: shows notification on whether session was created, updated or not changed at all
            long: verbose
            short: V
        - args:
            help: arguments to be passed as variables to the yaml file
            value_name: ARGUMENT
            multiple: true
  - kill:
      settings:
        - ColoredHelp
      about: Kill tmux session that matches the project
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            required: true
            index: 1
  - edit:
      settings:
        - ColoredHelp
      about: Create or edit a project
      alias: new
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            required: true
            index: 1
        - editor:
            help: the editor to use
            short: e
            long: editor
            required: true
            value_name: EDITOR
            env: EDITOR
        - no_check:
            help: do not check the project file
            short: C
            long: no-check
  - remove:
      settings:
        - ColoredHelp
      about: Remove a project (does not affect loaded tmux sessions)
      aliases:
        - rm
        - delete
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            required: true
            index: 1
        - no_input:
            help: do not prompt for input
            short: "y"
            long: no-input
