name: rmux
settings:
  - SubcommandRequired
  - VersionlessSubcommands
  - InferSubcommands
  - ColoredHelp
args:
  - config_dir:
      global: true
      help: configuration directory to use
      short: c
      long: config-dir
      value_name: DIR
      env: RMUX_CONFIG
subcommands:
  - list:
      settings:
        - ColoredHelp
      about: List all configured projects
      alias: ls
  - start:
      settings:
        - ColoredHelp
      about: Start a project as a tmux session
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            index: 1
        - template:
            help: template file for generating tmux commands
            short: m
            long: template
            value_name: TEMPLATE
        - attach:
            help: force attach the session
            short: a
            long: attach
            conflicts_with: no_attach
        - no_attach:
            help: don't automatically attach the session
            short: d
            long: no-attach
        - verbose:
            help: shows notification on whether session was created, updated or not changed at all
            long: verbose
            short: V
        - args:
            help: arguments to be passed as variables to the yaml file
            value_name: ARGUMENT
            multiple: true
        - tmux_command:
            global: true
            help: tmux command to use
            short: t
            long: command
            value_name: COMMAND
            env: RMUX_COMMAND
  - debug:
      settings:
        - ColoredHelp
      about: only print tmux command source without actually running tmux
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            index: 1
        - template:
            help: template file for generating tmux commands
            short: m
            long: template
            value_name: TEMPLATE
        - attach:
            help: force attach the session (ignored)
            short: a
            long: attach
            conflicts_with: no_attach
        - no_attach:
            help: don't automatically attach the session (ignored)
            short: d
            long: no-attach
        - verbose:
            help: shows notification on whether session was created, updated or not changed at all
            long: verbose
            short: V
        - args:
            help: arguments to be passed as variables to the yaml file
            value_name: ARGUMENT
            multiple: true
        - tmux_command:
            global: true
            help: tmux command to use
            short: t
            long: command
            value_name: COMMAND
            env: RMUX_COMMAND
  - kill:
      settings:
        - ColoredHelp
      about: Kill tmux session that matches the project
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            index: 1
        - args:
            help: arguments to be passed as variables to the yaml file
            value_name: ARGUMENT
            multiple: true
        - tmux_command:
            global: true
            help: tmux command to use
            short: t
            long: command
            value_name: COMMAND
            env: RMUX_COMMAND
  - edit:
      settings:
        - ColoredHelp
      about: Create or edit a project
      alias: new
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            index: 1
        - extension:
            help: the extension to use for the project file (yml|yaml|json)
            short: e
            long: ext
            value_name: EXT
            default_value: yml
        - editor:
            help: the editor to use
            short: E
            long: editor
            required: true
            value_name: EDITOR
            env: EDITOR
        - no_check:
            help: do not check the project file
            short: C
            long: no-check
        - args:
            help: arguments to be passed as variables to the yaml file when checking
            value_name: ARGUMENT
            multiple: true
        - tmux_command:
            global: true
            help: tmux command to use when checking
            short: t
            long: command
            value_name: COMMAND
            env: RMUX_COMMAND
  - remove:
      settings:
        - ColoredHelp
      about: Remove a project (does not affect loaded tmux sessions)
      aliases:
        - rm
        - delete
      args:
        - project_name:
            help: name of the project
            value_name: PROJECT_NAME
            required: true
            index: 1
        - no_input:
            help: do not prompt for input
            short: "y"
            long: no-input
